### ISSUE TITLE
Rounding error somewhere in the scale3d() transform on the image-canvas-wrapper element

### ISSUE THREAD

**Issue by NielsLeenheer** [pqina/filepond-plugin-image-preview#33]
There is sometimes a black line on the right side of the image preview. For example: 
<img width="509" alt="Screenshot 2020-04-25 at 13 06 13" src="https://user-images.githubusercontent.com/233230/80278378-04deab80-86f6-11ea-8976-e8c9a5b3c949.png">

The reason is that the scale3d() transform on the `filepond--image-canvas-wrapper` is slightly to small for the size of the `filepond--image-preview` element.

In the example above:

`filepond--image-preview`
The width set to `100%`
Using the inspector measured at 424.500px

`filepond--image-clip`
The width set to `424.138px`
Using the inspector measured at 424.125px ?!?!

`filepond--image-canvas-wrapper`
The width is set to `800px`.
The transform of `image-canvas-wrapper` is `scale3d(0.530172,0.530172,0)`
This results is a size of 424.1376px.

**Comment by NielsLeenheer** [comment]
As a - not so pretty - workaround, I've added the following custom CSS:

```css
        .filepond--image-clip {
            transform: translate3d(0px, 0px, 0px) scale3d(1.002, 1.002, 1) !important;
            transform-origin: top left;
        }
```
