### ISSUE TITLE
Overlay doesn't open properly...

### ISSUE THREAD

**Issue by thiagomajesk** [pqina/filepond-plugin-image-preview#67]
If you are using a big form on the page and the file pond is for instance, at the end of the form. After opening the preview, the overlay opens up at the start of the page.

![image](https://user-images.githubusercontent.com/13930952/228068920-a78f4326-95f1-49ec-ba6d-48f74a56d464.png)

The problem gets worse because the user can now click multiple times in the preview and open many overlays on top of each other (because you can still interact with the page behind).

If I change the overlay position from `absolute` to `fixed` it now behaves correctly, although the background is still scrollable:

```css
.filepond--fullsize-overlay {
  position: fixed;
  backdrop-filter: blur(2px);
}
```
