### ISSUE TITLE
Optional overlays background colors

### ISSUE THREAD

**Issue by npulidom** [pqina/filepond-plugin-image-preview#7]
It would be nice to be able to change the overlays background colors.

Colors are hardcoded
```javascript
drawTemplate(overlayTemplateSuccess, width, height, [54, 151, 99], 1);
```
Thanks for such a great plugin.

**Comment by rikschennink** [comment]
Good point! I'm working on switching the overlay to an SVG so the color can be set with CSS. Should be online later this week.

**Comment by rikschennink** [comment]
Just published version `2.0.0` of the image preview plugin. Still need to document the properties but you can now alter the color of the overlay gradient using the following CSS (note these are the default colors).

```css
.filepond--image-preview-overlay-idle {
    color: rgba(40, 40, 40, 0.85);
}

.filepond--image-preview-overlay-success {
    color: rgb(54, 151, 99);
}

.filepond--image-preview-overlay-failure {
    color: rgb(196, 78, 71);
}
```
